const CACHE_NAME="ssc-jagrat-shell-v19";
const OFFLINE_URL="offline.html";
const SHELL_FILES=["index.html","batch.html","subject.html","class.html","login.html","account.html","dashboard.html","performance.html","progress-report.html","mistake-book.html","revision.html","personalized-learning.html","daily-challenge.html","exam-simulator.html","question-bank.html","ai-study-assistant.html","daily.html","leaderboard.html","reset-password.html","notification-settings.html","help.html","offline.html","manifest.json","assets/style.css","assets/theme.js","assets/app.js","assets/class.js","assets/subject.js","assets/auth.js","assets/account.js","assets/supabase.js","assets/config.js","assets/menu.js","assets/access-popup.js","assets/pwa.js","assets/offline-store.js","assets/question-bank.js","assets/dashboard.js","assets/performance.js","assets/progress-report.js","assets/mistake-book.js","assets/revision.js","assets/personalized.js","assets/daily-challenge.js","assets/exam-simulator.js","assets/ai-study-assistant.js","assets/daily.js","assets/leaderboard.js","assets/reset-password.js","assets/notification-settings.js","assets/push-config.js","assets/push-notifications.js","assets/streak.js","assets/telegram-popup.js","assets/icons/icon-192.png","assets/icons/icon-512.png","assets/icons/icon-maskable-512.png","assets/icons/apple-touch-icon.png","assets/icons/logo.png","assets/icons/logo-header.png","assets/parmar-gk-batch-4.jpg"];
self.addEventListener("install",e=>{e.waitUntil(caches.open(CACHE_NAME).then(c=>c.addAll(SHELL_FILES)).catch(()=>{}));self.skipWaiting();});
self.addEventListener("activate",e=>{e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE_NAME).map(k=>caches.delete(k)))));self.clients.claim();});
self.addEventListener("push", event => {
  let data = {}; try { data = event.data ? event.data.json() : {}; } catch (_) {}
  const title = data.title || "SSC With Jagrat";
  const options = { body: data.body || "Your study reminder is ready.", icon: "assets/icons/icon-192.png", badge: "assets/icons/icon-192.png", data: { url: data.url || "dashboard.html", kind: data.kind || "study" }, tag: "ssc-jagrat-" + (data.kind || "study"), renotify: true };
  event.waitUntil(self.registration.showNotification(title, options));
});
self.addEventListener("notificationclick", event => { event.notification.close(); const target = new URL(event.notification.data?.url || "dashboard.html", self.location.origin).href; event.waitUntil(clients.matchAll({type:"window", includeUncontrolled:true}).then(list => { for (const c of list) { if ("focus" in c) { c.navigate(target); return c.focus(); } } return clients.openWindow(target); })); });
self.addEventListener("fetch",e=>{const req=e.request;if(req.method!=="GET")return;const u=new URL(req.url);if(u.origin!==self.location.origin)return;if(req.mode==="navigate"){e.respondWith(fetch(req).then(res=>{caches.open(CACHE_NAME).then(c=>c.put(req,res.clone()));return res;}).catch(()=>caches.match(req).then(r=>r||caches.match(OFFLINE_URL))));return;}e.respondWith(caches.match(req).then(cached=>{const net=fetch(req).then(res=>{if(res.ok)caches.open(CACHE_NAME).then(c=>c.put(req,res.clone()));return res;}).catch(()=>cached);return cached||net;}));});
